# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: '^(.tox/|docs/source/conf.py|setup.py)'
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      #- id: check-symlinks
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-toml
      - id: check-yaml
        exclude: '.pep8speaks.yml'
      #- id: check-json

  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        name: "Format code"
        language_version: python3
        files: redis_ipc.py

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    - id: mypy
      args:
        - --follow-imports=normal
        - --install-types
        - --non-interactive
      additional_dependencies:
        - "redis"
      files: redis_ipc.py

  - repo: "https://github.com/asottile/blacken-docs"
    rev: "1.16.0"
    hooks:
      - id: "blacken-docs"
        name: "Format docs (blacken-docs)"
        args: ["-l", "64"]
        additional_dependencies:
          - "black==23.1.0"

  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        #exclude: CHANGELOG\.rst$
        args:
          - '--max-line-length=90'

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
        #exclude: CHANGELOG\.rst$
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        files: redis_ipc.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
        files: redis_ipc.py

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-ll", "-q", "-r"]
        files: redis_ipc.py

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args:
          - --force-function-style
          - 'paronly'
          - --indent-size
          - '4'
