codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 5%
        if_not_found: success
    changes: no

  precision: 2
  round: nearest
  range: 80...100

  notify:
    irc:
      default:
        server: "irc.libera.chat"
        channel: '##code-hell'
        branches: null  # all branches by default
        threshold: 1%
        message: "Coverage {{changed}} for {{owner}}/{{repo}}"  # customize the message
        flags: null
        paths: null

ignore:
 - "scripts/.*"
 - "test_*.*"
 - ".tox/.*"
 - "*.rst"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  # layout: "reach, diff, flags, tree"
  branches: null
  behavior: default
  require_changes: no
