[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
branch = true
source = ["redis_ipc.py"]

[tool.coverage.paths]
source = ["./"]

[tool.coverage.report]
fail_under = 95
show_missing = true

[tool.black]
line-length = 84
include = 'redis_ipc.py'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
