name: Security check - Bandit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Run bandit
      uses: ioggstream/bandit-report-artifacts@v0.0.2
      with:
        project_path: redis_ipc.py
        ignore_failure: true
