name: Security check - Bandit

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Run bandit
      uses: VCTLabs/bandit-report-artifacts@v2
      with:
        project_path: redis_ipc.py
        config_file: pyproject.toml
