name: Security check - Bandit

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6

    - name: Run bandit
      uses: VCTLabs/bandit-report-artifacts@v3
      with:
        project_path: redis_ipc.py
        config_file: pyproject.toml
