name: Smoke

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PYTHONIOENCODING: utf-8
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install redis (ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -yqq redis-server
        sudo systemctl stop redis

    - name: Install redis (macos)
      if: runner.os == 'macOS'
      run: |
        brew tap homebrew/services
        brew install redis
        brew services stop redis

    - uses: actions/setup-python@v4.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Setup annotations on Linux
      if: runner.os == 'Linux'
      run: python -m pip install pytest-github-actions-annotate-failures

    - name: Run tests
      run: |
        tox
      env:
        PLATFORM: ${{ matrix.os }}

    - name: Build sdist/wheel
      run: |
        tox -e build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./dist/*.whl
