name: Smoke

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PYTHONIOENCODING: utf-8
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install redis (ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -yqq redis-server

    - name: Install redis (macos)
      if: runner.os == 'macOS'
      run: |
        brew install redis

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Run tests
      run: |
        tox
      env:
        PLATFORM: ${{ matrix.os }}

    - name: Code Coverage Summary Report
      if: runner.os == 'Linux'
      uses: irongut/CodeCoverageSummary@v1.0.1
      with:
        filename: coverage.xml
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2.1.0
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Build sdist/wheel
      run: |
        tox -e build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist/*.whl
