name: Pylint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  pylint:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4.3.1
      with:
        python-version: 3.8

    - name: Install tox
      run: |
        python -m pip install --upgrade pip wheel
        pip install tox

    - name: Run pylint
      run: |
        tox -e lint
